### ISSUE TITLE
get errors on windows

### ISSUE THREAD

**Issue by zhouweiming** [Urthen/case-sensitive-paths-webpack-plugin#7] opened 2016-07-28 08:03 UTC
I just had errors on windows when i run the demo.

```
WARNING in ./~/.npminstall/react/15.2.1/react/lib/traverseAllChildren.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

WARNING in E:/case-sensitive-paths-webpack-plugin/demo/~/.npminstall/react/15.2.1/react/lib/traverseAllChildren.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

WARNING in ./~/.npminstall/react/15.2.1/react/lib/getIteratorFn.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

WARNING in E:/case-sensitive-paths-webpack-plugin/demo/~/.npminstall/react/15.2.1/react/lib/getIteratorFn.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.
```

Please help me.

**Comment by Urthen** [comment] 2016-08-03 15:45
Hi Zhouweiming,

Unfortunately I don't have a windows system to test on, but it looks like you've already isolated that to being a problem with webpack in windows. I'm going to close this for now, but feel free to reopen if you determine this plugin is the cause.

**Closed by Urthen** 2016-08-03 15:45 UTC

**Comment by zhouweiming** [comment] 2016-08-06 07:28
Thanks for your reply.  I have given up to solve and start develop on mac. I think this problem should be resolved on node level, because I get more puzzling warnings.  

https://stackoverflow.com/questions/38656250/webpack-warning-on-windows-there-is-another-module-with-an-equal-name-when-cas
