### ISSUE TITLE
"File does not exist" is confusing

### ISSUE THREAD

**Issue by gaearon** [Urthen/case-sensitive-paths-webpack-plugin#19] opened 2017-05-17 18:38 UTC
When I switch between branches, I often see messages like this:

>Module not found: [CaseSensitivePathsPlugin] `/Users/dan/p/create-react-app/packages/react-scripts/template/src/service-worker-registration.js` does not match the corresponding path on disk - File does not exist.

Note how it starts with the case sensitive plugin intro, but then the real issue is that **the file just stopped existing**. So the message is misleading until the very last four words.

Shouldn't the plugin just bail out if a file was deleted, and ignore it? Then webpack can show its normal message about file missing.

**Comment by Urthen** [comment] 2017-05-17 18:54
I could probably make the plugin detect when this occurs and completely stop attempting to enforce anything, since presumably your build is about to fail anyway. Would that work?

**Comment by gaearon** [comment] 2017-05-17 18:56
Yes, thanks!

**Comment by gaearon** [comment] 2017-05-20 23:58
I've also been getting these more often, unfortunately in cases when file **does** exist. (But didn't exist at some point in the past.)

<img width="1069" alt="screen shot 2017-05-21 at 00 56 45" src="https://cloud.githubusercontent.com/assets/810438/26280147/7d03859a-3dc0-11e7-8470-d0873e6a6f9f.png">


Any chance you could look at this soon? I might try to roll back to an earlier version since I don't think this happened with 1.x.

**Comment by gaearon** [comment] 2017-05-21 19:39
I reverted to 1.1.4 which doesn't have this issue (or at least doesn't reproduce as often).
In particular, here's what reproduced it for me in 2.0.0:

1. Import a file that doesn't exist
2. Create that file

In 1.1.4, it compiles successfully after the file is created, but not in 2.0.0.

**Comment by Urthen** [comment] 2017-05-30 14:45
I'm going to try and look at these issues this week. Sorry for taking so long, but I switched jobs and don't actually use this code anymore. I'll try to help out for those who still do though :-)

**Comment by gaearon** [comment] 2017-05-30 14:50
No worries 😛 
Thanks for still taking a look!

**Comment by caesarsol** [comment] 2017-05-30 15:36
I think this may actually be a duplicate of https://github.com/Urthen/case-sensitive-paths-webpack-plugin/issues/17 😄 

I think it could be enough to juste delete the FS caching code, as webpack2 has a special `fs` module with integrated caching (as far as I understood, please any webpack expert verify this).

I could take a look if @Urthen doesn't find the time!

**Comment by Urthen** [comment] 2017-05-30 16:03
I think I have it now, I'm still working on hardening tests. One is still
intermittently failing for no good rain.

**Comment by Urthen** [comment] 2017-05-30 18:56
Published 2.1.0 which as you mentioned *should* fix both this and #17. Can you give it a test?

**Comment by Urthen** [comment] 2017-05-30 21:10
Scratch that, try with 2.1.1 -- .0 had problems with older versions of node.

**Closed** 2017-08-08 16:57 UTC
