### ISSUE TITLE
Increase verbosity for "Module not found" errors

### ISSUE THREAD

**Issue by caesarsol** [Urthen/case-sensitive-paths-webpack-plugin#18] opened 2017-05-08 07:11 UTC
Hello @Urthen,
do you think something like this is in scope with your module?

https://github.com/facebookincubator/create-react-app/issues/1278

Thank you!

**Comment by Urthen** [comment] 2017-05-10 16:52
Hi @caesarsol -

Could you describe in more detail exactly what functionality you're looking for?

Thanks!

**Comment by Urthen** [comment] 2017-05-30 15:31
I believe this is a duplicate of #19, if not please add more info and re-open.

**Closed by Urthen** 2017-05-30 15:31 UTC
